# Generated by Django 3.2.8 on 2022-01-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='turno',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Mañana'), (2, 'Tarde'), (3, 'Noche')], null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='inscriptos',
            field=models.IntegerField(verbose_name='inscriptos'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nombre',
            field=models.CharField(max_length=128, verbose_name='Nombre'),
        ),
    ]
